# Generated by Django 4.0.1 on 2022-01-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemons',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='pokemons',
            old_name='nome',
            new_name='Nome',
        ),
    ]
