# Generated by Django 4.0.1 on 2022-01-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_rename_id_pokemons_id_rename_nome_pokemons_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemons',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pokemons',
            old_name='Nome',
            new_name='nome',
        ),
    ]
