# Generated by Django 4.0.1 on 2022-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_rename_id_pokemons_id_rename_nome_pokemons_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='nome',
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
